name: Update Fork

on:
  schedule:
    - cron: '0 * * * *' # Запуск каждый час
  workflow_dispatch: # Ручной запуск

jobs:
  update-fork:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fork
        uses: actions/checkout@v3
        with:
          ref: master # Заменено на master
          fetch-depth: 0 # Клонировать всю историю

      - name: Set Upstream
        run: |
          git remote add upstream https://github.com/cagnulein/qdomyos-zwift.git
          git fetch upstream
          git merge upstream/master --no-edit # Заменено на master
          git push origin master # Заменено на master

      - name: Debug Git Remotes
        run: |
          git remote -v
         
